### ISSUE TITLE
Problem running docker-chromium-xvfb

### ISSUE THREAD

**Issue by rogthedodge** [mark-adams/docker-chromium-xvfb#14]
Hi

Running a python test script, I get:

Traceback (most recent call last):
  File "mcanvas-login-test.py", line 19, in testLogin
    element.send_keys(os.getenv('MCANVAS_TEST_EMAIL'))
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 320, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT, {'value': keys_to_typing(value)})
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: an X display is required for keycode conversions, consider using Xvfb
  (Session info: chrome=52.0.2743.116)
  (Driver info: chromedriver=2.19.346067 (6abd8652f8bc7a1d825962003ac88ec6a37a82f1),platform=Linux 4.4.14-moby x86_64)

Any ideas? I tried just going to a page and checking the page title and everything worked, so I thin it's all installed OK.

Thanks, Roger

**Comment by mark-adams** [comment]
That seems strange. Can you include your Dockerfile, your test script, and the docker command that you're using to execute it so that I can help more?

**Comment by herryliq** [comment]
I had a same problem, I had solved with follows script in Dockerfile:
export DISPLAY=:1
Xvfb $DISPLAY -ac -screen 0 1280x1024x8 &
sleep 1

the stackoverflow url:
http://stackoverflow.com/questions/25731647/protractor-sendkeys-not-working-an-x-display-is-required-for-keycode-conversion

**Comment by mark-adams** [comment]
I tested this with the latest images on my sample applications (samples/python2, samples/python3) and everything appears to be working fine.

@rogthedodge, without a copy of your Dockerfile and script, I'm not sure there's much more to do on this one. Please reopen if you still are experiencing the issue.

**Comment by chatrapathik** [comment]
Hii adams,
 - When I ran selenium test case using docker i got this error:
```test_google_title_matches_correct_value (test_google.ExampleTests) ... ERROR

======================================================================
ERROR: test_google_title_matches_correct_value (test_google.ExampleTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_google.py", line 13, in test_google_title_matches_correct_value
    input_box.send_keys('apple', Keys.RETURN)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 349, in send_keys
    'value': keys_to_typing(value)})
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 493, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: an X display is required for keycode conversions, consider using Xvfb
  (Session info: chrome=57.0.2987.98)
  (Driver info: chromedriver=2.28.455506 (18f6627e265f442aeec9b6661a49fe819aeeea1f),platform=Linux 3.13.0-38-generic x86_64)


----------------------------------------------------------------------
Ran 1 test in 14.391s

FAILED (errors=1)

```
- This is my docker file code:
```
 FROM markadams/chromium-xvfb
 
 RUN apt-get update && apt-get install -y \
     python python-pip curl unzip libgconf-2-4
 
 RUN pip install pytest selenium
 
 ENV CHROMEDRIVER_VERSION 2.28
 ENV CHROMEDRIVER_SHA256 8f5b0ab727c326a2f7887f08e4f577cb4452a9e5783d1938728946a8557a37bc
 
 RUN curl -SLO "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip" \
   && echo "$CHROMEDRIVER_SHA256  chromedriver_linux64.zip" | sha256sum -c - \
   && unzip "chromedriver_linux64.zip" -d /usr/local/bin \
   && rm "chromedriver_linux64.zip"
 
 RUN mkdir chatra
 ADD . chatra/
 WORKDIR chatra/
 CMD python -m unittest -v test_google
 
 

```
- This is my test case:
```python
import unittest
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

class ExampleTests(unittest.TestCase):

    def setUp(self):
        self.driver = webdriver.Chrome('/usr/local/bin/chromedriver')

    def test_google_title_matches_correct_value(self):
        self.driver.get("http://www.google.com")
        input_box = self.driver.find_element_by_id('lst-ib')
        input_box.send_keys('apple', Keys.RETURN)
        assert "Google" in self.driver.title
        self.driver.save_screenshot('google.png')

    def tearDown(self):
        self.driver.close()
                                                                     

```
- How can we resolve the above issue? And how can we use chrome driver version (2.29).
