### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by pimterry** [mark-adams/docker-chromium-xvfb#2]
I'd quite like to reuse some of this in one of my projects (specifically: your xvfb-chromium script), but you don't include any licensing details in the repo, so I technically can't.

Assuming that you intended this to be open-source, any chance you could drop in an appropriate license?

**Comment by mark-adams** [comment]
Absolutely! https://github.com/mark-adams/docker-chromium-xvfb/blob/master/LICENSE

**Comment by pimterry** [comment]
Awesome, thanks!
