### ISSUE TITLE
No such file or directory, open '/app/package.json'

### ISSUE THREAD

**Issue by smoakey** [mark-adams/docker-chromium-xvfb#8]
When using your "onbuild" js container I always get:

no such file or directory, open '/app/package.json'

I think this has to do with the fact that this container extends the base container which sets the WORKDIR as /app but npm install needs to be run from /app/src?

**Comment by davidwesst** [comment]
Pull Request #11 has been submitted for review.

I've setup a clone where `js-onbuild` and `base` are tagged. You can find it here on [docker hub](https://hub.docker.com/r/davidwesst/docker-chromium-xvfb/).

**Comment by smoakey** [comment]
I believe this is done! thanks @davidwesst @mark-adams
